stages:
  - stage:
    displayName: Test and Build on Windows
    pool:
      vmImage: windows-latest
    jobs:
      - job: Windows
        steps:
          - template: test/azure-pipelines/win32/azure-pipelines.yml
  - stage:
    displayName: Test and Build on Linux
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: Linux
        steps:
          - template: test/azure-pipelines/linux/azure-pipelines.yml
      - job: Docker
        dependsOn: Linux
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        steps:
          - template: test/azure-pipelines/docker/azure-pipelines.yml
