jobs:
- job: Windows
  pool:
    vmImage: windows-latest
  steps:
  - template: script/test/win32/azure-pipelines.yml
- job: Linux
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: script/test/linux/azure-pipelines.yml
