variables:
  - group: docker # including $DOCKER_USER and $DOCKER_TOKEN
  - group: go     # including $GO_VERSION

stages:
  - stage:
    displayName: On Windows
    pool:
      vmImage: windows-latest
    jobs:
      - job: Windows
        steps:
          - template: test/azure-pipelines/win32/azure-pipelines.yml
  - stage:
    displayName: On Linux
    # Removes the implicit dependency and run in parallel
    dependsOn: []
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: Linux
        steps:
          - template: test/azure-pipelines/linux/azure-pipelines.yml
      - job: Docker
        dependsOn: Linux
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        steps:
          - template: test/azure-pipelines/docker/azure-pipelines.yml
