jobs:
- job: Windows
  pool:
    vmImage: windows-latest
  steps:
  - template: test/azure-pipelines/win32/azure-pipelines.yml
- job: Linux
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: test/azure-pipelines/linux/azure-pipelines.yml
