name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Run tests
        run: |
          go mod download
          cp src/config/example.ini ~/fyj.ini
          make test
          make cover

      - name: Compile and build
        run: |
          make
          make web
