on: workflow_call

jobs:
  deploy-docker:
    name: Deploy Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetche Latest Image
        run: |
          docker pull golang:alpine || true
          docker pull alpine:latest || true

      - name: Build Docker Image
        run: |
          docker build --no-cache -t fyj:latest .

      # Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push to Docker Hub
        run: |
          docker tag fyj:latest ${{ vars.DOCKER_USER }}/fyj:latest
          docker push ${{ vars.DOCKER_USER }}/fyj:latest

      # GitHub Container registry (ghcr.io)
      - name: Login GitHub Container
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Container
        run: |
          docker tag fyj:latest ghcr.io/${{ github.repository_owner }}/fyj:latest
          docker push ghcr.io/${{ github.repository_owner }}/fyj:latest
