on: workflow_call

jobs:
  test-windows:
    name: Test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
          cache: false

      - name: Install protoc tools
        run: |
          scoop install protobuf
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Run tests
        run: |
          go generate ./...
          go mod download
          go mod tidy
          make test
          make cover

      - name: Compile and build
        run: |
          make

      - name: Build Inno Setup Installer
        run: |
          iscc .\script\windows\go-xn.iss

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-amd64
          path: build/dist/
