on: workflow_call

jobs:
  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Run tests
        run: |
          go mod download
          go mod tidy
          cp src/config/example.ini ~/fyj.ini
          make test
          make cover

      - name: Compile and build
        run: |
          make
