on: workflow_call

jobs:
  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
          cache: false

      - name: Set environment variables
        run: |
          echo "GOOS=$(go env GOOS)" >> $GITHUB_ENV
          echo "GOARCH=$(go env GOARCH)" >> $GITHUB_ENV

      - name: Run tests
        run: |
          go mod download
          go mod tidy
          make test
          make cover

      - name: Compile and build
        run: |
          make

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GOOS }}-${{ env.GOARCH }}
          path: build/
