on: workflow_call

jobs:
  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
          cache: false

      - name: Install protoc tools
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Run tests
        run: |
          go generate ./...
          go mod download
          go mod tidy
          make test
          make cover

      - name: Compile and build
        run: |
          make

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-amd64
          path: build/
