name: test

on:
  push:
    paths-ignore:
      - 'test/azure-pipelines/**'
      - 'azure-pipelines.yml'
  pull_request:
    paths-ignore:
      - 'test/azure-pipelines/**'
      - 'azure-pipelines.yml'

jobs:
  test-linux:
    uses: ./.github/workflows/test.linux.yml

  test-windows:
    uses: ./.github/workflows/test.windows.yml

  deploy-docker:
    needs: test-linux
    if: github.event_name == 'push'
    uses: ./.github/workflows/test.docker.yml
    secrets: inherit
