name: test

on: [push, pull_request]

jobs:
  test-linux:
    uses: ./.github/workflows/test.linux.yml

  test-windows:
    uses: ./.github/workflows/test.windows.yml

  deploy-docker:
    needs: test-linux
    if: github.event_name == 'push' && github.ref_name == 'main'
    uses: ./.github/workflows/test.docker.yml
    secrets: inherit
