on: workflow_call

jobs:
  test-windows:
    name: Test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
          cache: false

      - name: Set environment variables
        run: |
          echo "GOOS=$(go env GOOS)" >> $env:GITHUB_ENV
          echo "GOARCH=$(go env GOARCH)" >> $env:GITHUB_ENV

      - name: Run tests
        run: |
          go mod download
          go mod tidy
          make test
          make cover

      - name: Compile and build
        run: |
          make

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GOOS }}-${{ env.GOARCH }}
          path: build/

      - name: Build Inno Setup Installer
        run: |
          iscc script/windows/go-xn.iss

      - name: Publish Installer Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GOOS }}-${{ env.GOARCH }}-installer
          path: build/*-setup.exe
