name: test

on:
  push:
    paths-ignore:
      - 'test/azure-pipelines/**'
      - 'azure-pipelines.yml'
  pull_request:
    paths-ignore:
      - 'test/azure-pipelines/**'
      - 'azure-pipelines.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x

      - name: Run tests
        run: |
          go mod download
          go mod tidy
          cp src/config/example.ini ~/fyj.ini
          make test
          make cover

      - name: Compile and build
        run: |
          make
